language:
    - cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qt5-default qttools5-dev-tools qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    
script:
    - qmake -v
    - make