language:
    - cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository --yes "deb http://archive.ubuntu.com/ubuntu trusty main"
    - sudo add-apt-repository --yes "deb http://archive.ubuntu.com/ubuntu trusty universe"
    - sudo apt-get install -y aptitude
    - sudo aptitude update -q

install:
    - sudo aptitude install -y qt5-default libtesseract-dev
    
script:
    - qmake
    - make
